#!/usr/bin/env bash
set -e

[ -d ./bats/bin ] && export PATH=./bats/bin:"$PATH"

STATUS=0
bats -t test || STATUS="$?"

if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then
  ./script/mirror update "$TRAVIS_COMMIT_RANGE"
elif [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
  ./script/mirror verify "$TRAVIS_COMMIT_RANGE"
fi

exit "$STATUS"
