#!/usr/bin/env bash

set -e

if [ $# -ne 2 ]; then
  echo "usage: $0 VERSION RELEASE_DIRECTORY"
  exit 1
fi

version="$1"
release_directory="$2"
file="share/ruby-build/truffleruby-${version}"

add_platform() {
  platform="$1"
  basename="truffleruby-${version}-${platform}.tar.gz"
  url="https://github.com/oracle/truffleruby/releases/download/vm-${version}/${basename}"
  sha256=$(sha256sum "$release_directory/$basename" | cut -d ' ' -f 1)

  cat >> "$file" <<EOS
  install_package "truffleruby-${version}" "${url}#${sha256}" truffleruby
EOS
}

cat > "$file" <<EOS
install_package "openssl-1.1.1b" "https://www.openssl.org/source/openssl-1.1.1b.tar.gz#5c557b023230413dfb0756f3137a13e6d726838ccd1430888ad15bfb2b43ea4b" mac_openssl --if has_broken_mac_openssl

if is_mac; then
EOS
add_platform "macos-amd64"
echo "else" >> "$file"
add_platform "linux-amd64"
echo "fi" >> "$file"
