#!/usr/bin/env bash

set -e

if [ $# -ne 1 ]; then
  echo "usage: $0 VERSION"
  exit 1
fi

version="$1"
file="share/ruby-build/truffleruby-${version}"

add_platform() {
  platform="$1"
  basename="truffleruby-${version}-${platform}.tar.gz"
  url="https://github.com/oracle/truffleruby/releases/download/vm-${version}/${basename}"
  sha256=$(curl -L "$url" | sha256sum | cut -d ' ' -f 1)

  cat >> "$file" <<EOS
  install_package "truffleruby-${version}" "${url}#${sha256}" truffleruby
EOS
}

cat > "$file" <<EOS
install_package "openssl-1.1.0j" "https://www.openssl.org/source/openssl-1.1.0j.tar.gz#31bec6c203ce1a8e93d5994f4ed304c63ccf07676118b6634edded12ad1b3246" mac_openssl --if has_broken_mac_openssl

if is_mac; then
EOS
add_platform "macos-amd64"
echo "else" >> "$file"
add_platform "linux-amd64"
echo "fi" >> "$file"
